services:
  safelang:
    build: .
    platform: linux/amd64
    ports:
      - "2113:2112"
    restart: unless-stopped
    cpus: 1
    pids_limit: 64
    mem_limit: 512m
    environment:
      - FLAG=ctfcup{0925ec82911c7c073f60e86b17797756}
