services:
  safelang:
    build: .
    platform: linux/amd64
    ports:
      - "2114:2112"
    restart: unless-stopped
    cpus: 1
    pids_limit: 64
    mem_limit: 512m
    environment:
      - FLAG=ctfcup{de474f95035a592f2e9feb1f95ccc102}
